# 存储设置
leveldb:
  folder: leveldb/message.db
  charset: utf-8

# 消息队列服务端口
xymq:
  port: 8686
  backLog: 128
  storage:
    type: levelDb
# thread: 推送消息的线程池配置
#   corePoolSize: 75
#   maxPoolSize: 200
#   queueCapacity: 1000
#   keepAliveSeconds: 300
